##################
# cfgs for STL10 #
##################

# args for network
net_avgpool_size: 7
net_heads:
  - 70
  - 10

# args for dataset and dataloader
dataset: stl10
data_root: data/stl-10
tfm_means: (0.485, 0.456, 0.406)
tfm_stds: (0.229, 0.224, 0.225)
tfm_size: (96, 96)
tfm_resize: 112

# smaller batch size for lower memory consumption
batch_size: 128
